### ISSUE TITLE
Alternative VS Code color highlighting

### ISSUE THREAD

**Issue by vladdeSV** [vladdeSV/vscode-klog#1]
Currently, most of the syntax definition begins with `markup.other.____` (eg. `markup.other.duration.should-total.klog`). Because the top-level tokens are the same, there are no visible differences to properly indicate the type of field.

For instance, all the following lines currently shows up in the default text color.

```klog
  30m foo            // markup.other.duration.positive.klog
  -10m bar           // markup.other.duration.negative.klog
  00:00 - 01:00 baz  // markup.other.timespan.klog
```

However, `klog print <file>` clearly differentiates between durations (positive and negative), time spans, and summaries.

---

The following tokens are recognized, but not colorized properly:
- `keyword.other.tag.klog`
- `string.unquoted.summary.behind-entry.klog`
- `string.unquoted.summary.after-date.klog`
- `markup.heading.date.klog`
- `markup.other.timespan.klog`
- `markup.other.timespan.open-ended.klog`
- `markup.other.duration.positive.klog`
- `markup.other.duration.negative.klog`
- `markup.other.duration.should-total.klog`

Although not directly addressable yet, some illegal characters are highlighted
- `<00:00>` highlights the two <>, because such time is illegal
- Summary lines directly underneath a date which begin with a single space have the first character highlighted in red (subject to change)

**Comment by jotaen** [comment]
Ah, too bad, there indeed doesn’t seem to be a way in VSCode to account for the background color:

- [No background color styling via themes](https://github.com/Microsoft/vscode/issues/3429) (Still open)
- [No background-aware colouring](https://github.com/microsoft/vscode/issues/101418) (Won’t fix)

**Comment by acikek** [comment]
While it is unfortunate that most of the VSCode themes don't account for these tokens, there's nothing we can really do about it.

Honestly, the best approach would be to create a community theme for the language, that has support for the tokens in question.

**Comment by vladdeSV** [comment]
@acikek I do not believe a theme is the way to go.

Personally, I would never switch from a theme to another for one language. Especially if this theme is a dark theme, and I use a light one (and vice versa).

It may not be possible as of right now, but referencing already defined colors by the current theme is (in my opinion) the best approach.

**Comment by acikek** [comment]
@vladdeSV There could be a community dark and light theme, no?

Besides, different themes have different token matches. Referencing other unrelated tokens won't work for every theme; the whole thing will end up unintuitive.

**Comment by vladdeSV** [comment]
@acikek There could be, but I certainly would not use it. Unless, of course, the theme matches the theme I have right now.

For instance, if one person really likes *Monokai*, and someone else likes *Dark+*, whichever theme the community version is based upon, the other will have to switch for. This is undesirable for the end user.

> Referencing other unrelated tokens won't work for every theme;

You have a point here. I did not think of this. In my mind I assumed tokens were mapped to referenceable colors, but looking at [the default *Monokai* theme](https://github.com/microsoft/vscode/blob/a699ffaee62010c4634d301da2bbdb7646b8d1da/extensions/theme-monokai/themes/monokai-color-theme.json) they are mapped directly to color codes.

I do not like the idea of a theme you have to switch to just for *klog*.

**Comment by acikek** [comment]
There are ways to map specific colors to text without the usual TextMate syntax highlighting. Take [DenizenScript's syntax highlighting for reference](https://github.com/DenizenScript/DenizenVSCode). It's not a theme, it just adds customizable colors to elements, extending the current theme.
