### ISSUE TITLE
Icon and logo

### ISSUE THREAD

**Issue by vladdeSV** [vladdeSV/vscode-klog#2]
- `.klg` files should have a dedicated file icon in VS Code
- This extension should have an icon

AFAIK there are no icons for klog.

**Comment by vladdeSV** [comment]
@jotaen Are there any official file icons or a logo for Klog?

**Comment by jotaen** [comment]
Wow, what is happening here? This is really amazing! 🎉 I need to reference this somewhere – will figure out a good place to link to 3rd-party utilities, e.g. from the docs. Providing syntax-highlighting is really useful (I also might add one for sublime at some point, since I personally use that for text files.)

On-topic: There is no icon yet, but I agree it would be cool to have one. I’ve created [an issue in the klog repo](https://github.com/jotaen/klog/issues/6), so that we have a place for suggestions or discussion around it.

**Comment by vladdeSV** [comment]
Awesome.

Both VS Code and Sublime Text uses TextMate language files, so converting this to Sublime Text should not be a problem. I am pretty the snippets code can be easily converted as well.

**Comment by jotaen** [comment]
Have linked your repo in the docs: https://klog.jotaen.net/

**Comment by vladdeSV** [comment]
I am thinking something that is distinctly different from `klog` the program, and something that says `vscode-klog` the extension.

First draft (about as big as it will be shown in the extension selector in VS Code):
<img alt="icon klog draft 1" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/feature/icon/resource/klog%20icon.png" width="64">

Opinions @jotaen ?

**Comment by vladdeSV** [comment]
Second draft:
<img alt="icon klog draft 1" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/682c27b22e5c9dc507025e63961f1f411b0dddf2/resource/klog%20icon.png" width="64">

**Comment by vladdeSV** [comment]
The icon is visible in the README.md on branch [feature/icon](https://github.com/vladdeSV/vscode-klog/tree/feature/icon).

(It will always display the latest icon draft, as it's just pointing to the image in `resource/`)

**Comment by vladdeSV** [comment]
Above icons are for the extension icon only. I have not thought about the file icons yet,

**Comment by jotaen** [comment]
That looks very neat! I like the revision version better (i.e. more contrast, no drop shadow). Have you tried something with colours? (Just a quick sketch below)

![Untitled@0 5x](https://user-images.githubusercontent.com/3618384/111595109-13c9c300-87cc-11eb-8871-2f0cfcfeb263.png)

**Comment by vladdeSV** [comment]
The icon is slightly, very slightly, tinted blue to give a metallic look.

I will experiment a bit more with different colors.

**Comment by vladdeSV** [comment]
Third draft (slightly tinted blue, update insets):

<img alt="icon klog draft 1" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/058e7367e664cd6d06aa8a95bcf93bb174574a90/resource/klog%20icon.png" width="128">

**Comment by jotaen** [comment]
That looks quite terrific! 🎉

**Comment by vladdeSV** [comment]
Fourth draft (change border outline):

<img alt="icon klog draft 1" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/d841b260bc9da16becc96230d04c8c548c0a792f/resource/klog%20icon.png" width="128">

This will most likely be the final version. Thanks for the input @jotaen 🎉

**Comment by vladdeSV** [comment]
> This will most likely be the final version.

Okay, that was an complete and utter lie.

---

Fifth draft (klog-letter has own lighting effect, changed metallic shine shape):

<img alt="icon klog draft 5" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/9b896a28c837eea405674b379409e4362908600b/resource/klog%20icon.png" width="128">

I am pretty sure I will get back to changing the lighting effect again, but leaving the icon as it is for now.

**Comment by vladdeSV** [comment]
Seems like there is no way to easily customize custom icons for specific file types. Just as with custom colors mentioned in #1, there seems to be no other way to specify custom file icons other than a whole new icon theme ([source](https://code.visualstudio.com/api/extension-guides/file-icon-theme)).

**Comment by vladdeSV** [comment]
According to https://github.com/Microsoft/vscode/issues/14662#issuecomment-352752951, the icon should be added to [jesseweed/seti-ui](https://github.com/jesseweed/seti-ui) in a PR.

**Comment by jotaen** [comment]
Haha oh god, that will probably never happen 😆

**Comment by vladdeSV** [comment]
@jotaen If I submit a PR, should I use the icon for the extension, or should I use the official icon?

If the latter, I'll look into what colors might be appropriate, as pure white or black might not go well with all themes.

**Comment by jotaen** [comment]
For the filetype itself I’d probably lean towards the “official” (simple) one then, if that’s okay with you.

Yeah, a colour would be terrific, happy to accept whatever you suggest 😸

**Comment by vladdeSV** [comment]
Awesome. I think the official one would be better as well. I'll keep you updated.

**Comment by jotaen** [comment]
Keen to see whether they’ll accept it, as the tool is pretty niche after all 😆

**Comment by vladdeSV** [comment]
For funsies, here is "The Evolution of the Extension Icon":


<img align="left" alt="icon klog draft 1" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/031989fb77e7e75bf0732a31e1e80beb5743f88d/resource/klog%20icon.png" width="128">
<img align="left" alt="icon klog draft 2" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/682c27b22e5c9dc507025e63961f1f411b0dddf2/resource/klog%20icon.png" width="128">
<img align="left" alt="icon klog draft 3" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/058e7367e664cd6d06aa8a95bcf93bb174574a90/resource/klog%20icon.png" width="128">
<img align="left" alt="icon klog draft 4" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/d841b260bc9da16becc96230d04c8c548c0a792f/resource/klog%20icon.png" width="128">
<img align="left" alt="icon klog draft 5" src="https://raw.githubusercontent.com/vladdeSV/vscode-klog/9b896a28c837eea405674b379409e4362908600b/resource/klog%20icon.png" width="128">

**Comment by vladdeSV** [comment]
> Happy to open a quick PR if you're accepting and think this would work.

I would love a PR @jgaehring 🙌

**Comment by jgaehring** [comment]
Here ya go!

- #46 

VS Code decided to give me all sorts of heartburn just when I opened it up to look at this (totally unrelated, as far as I can tell), so you probably want to pull it and check out that it works on your own system first, if you weren't planning to already. I couldn't debug/test it fully on account of that.
