### ISSUE TITLE
Better date detection

### ISSUE THREAD

**Issue by vladdeSV** [vladdeSV/vscode-klog#5]
Bogus dates such as `2021-99-99` are recognized as valid dates.

**Comment by vladdeSV** [comment]
(Because klog is a simplistic language, maybe this would be a good time to learn and implement a language server?)

**Comment by jotaen** [comment]
Should you really intend to build something like this, it might be worthwhile to explore to combine a language server with the CLI tool. It might be too much to include an actual server into the CLI itself, but (just as a thought) there could be “hidden” commands of the CLI that speak JSON or some other structured language. That way the parser functionality could be reused and wrapped into some sort of proxy server that talks to the editor plugin.

**Comment by jotaen** [comment]
(Just bouncing off thoughts here 😄 )

**Comment by vladdeSV** [comment]
I have no idea how to actually implement a language server. I am pretty sure all can be done within this extension.

The error messages when running 'klog print <file>'  are detailed, and I think that they can be parsed pretty easily. Without doing anything at all at your end, I could simply run that and check:
1. Did the command return `255` ?
2. If so, parse the error message

(Also just bouncing thoughts 😋)

**Comment by vladdeSV** [comment]
On-topic: one solution for this issue is to simply check all possible dates
```regexp
\d{4}-(0[13578]|1[02])-([012][0-9]|3[01])
\d{4}-(0[469]|11)-([012][0-9]|30)
\d{4}-02-([01][0-9]|2[0-9])
```

These will highlight all valid dates (including February the 29th, even on non-leap years)

**Comment by vladdeSV** [comment]
Added an issue for language server #4 @jotaen

**Comment by vladdeSV** [comment]
This seems like it is out of scope for a syntax highlighter.

I would very much prefer to see validation be done by a language server (see #7).
