### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by vladdeSV** [vladdeSV/vscode-klog#8]
Final push before v1.0 can be released.

[Blocking issues](/vladdeSV/vscode-klog/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0)

**Comment by vladdeSV** [comment]
@jotaen If you have time, could you please try out version `1.0.0-rc.2` ( `0.1.3` on VS Code Marketplace)?

If you find anything obvious (or less obvious), feel free to jot it down in this issue 😋

**Comment by vladdeSV** [comment]
Just noticed some minor problems. Will push a new update soon.

**Comment by vladdeSV** [comment]
Just released version `1.0.0-rc.3` (`0.1.4` on VS Code Marketplace)

**Comment by jotaen** [comment]
Have tried out all kinds of things, so far only one minor issue: tags in record summaries are not recognised if they appear at the beginning of a line

<img width="343" alt="Screenshot 2021-02-13 at 10 25 10" src="https://user-images.githubusercontent.com/3618384/107846678-d4334400-6de5-11eb-98b6-a9fd9b415af4.png">

**Comment by vladdeSV** [comment]
Fixed summaries hashtags in ad24a74ac979bd7824312d7c57d1acbcb6649fe8.

@jotaen It previously only matched if the first character was a "letter". Where this ever a part of the spec (eg. "[...] MUST begin with a "letter"), or was I just tired when I wrote that rule?

**Comment by jotaen** [comment]
I think it [used to say something similar](https://github.com/jotaen/klog/blob/5c8c3c69429960daee41f457e3e0261f4a173855/docs/Specification.md) for entry summaries, that might have been misleading.

**Comment by vladdeSV** [comment]
Ah! Found what I was looking for. But I implemented it in the wrong place anyway 😋

**Comment by vladdeSV** [comment]
Release candidate 4 is released, available as version `0.1.6` on VS Code marketplace

@jotaen If you have time this week, could you give the extension a spin again? This will most likely be the final RC before version `1.0`.

**Comment by jotaen** [comment]
👍  will do

**Comment by jotaen** [comment]
This looks awesome 🎉  I really like the snippets/placeholders, that’s super convenient. And the gif example in the README is very helpful.

I just noted down the following points, which are all quite minor I think:

- Would it be possible to colour the time values (i.e. the durations and time ranges)? They are currently default colour, so you don’t get any feedback whether they are syntactically correct or not. I thought it would be cool if they turn red or something, once they are recognised.
- The highlighter doesn’t complain about arbitrary indentation, so indenting with 5 spaces or 2 tabs still highlights the entry regularly, but actually that’s invalid syntax and doesn’t get parsed by klog.
- When you write `1h 1h test` as entry, or `8:00 - 9:00 - 10:00 test`, then it also highlights the redundant times, but actually they are already part of the summary.

**Comment by vladdeSV** [comment]
Thanks :)

Regarding the points: all of those I've had to work around.

The syntax highlighter was much "smarter" before, and was pretty good att detecting where something was wrong. It would highlight all text in red. But it was *too* good, so as soon as you started typing it would recognize something was not syntactically correct (see #12).

Unfortunately I have no good way to highlight the time duration / ranges. I want to categorize them according to [TextMate Language spec](https://macromates.com/manual/en/language_grammars#naming_conventions), and what I see best fit for those are `markup.other.*` (which is not highlighted by VS Code). I could change the naming conventions so it would be better highlighted, but it is not recommended by the spec.

The plan is for the syntax highlighter to be a helping hand, but not much more. In version v1.1 (someday) to have a basic language parser using the *klog* binary. Any problems will detected by *klog*, which in the long run is for the better.

**Comment by jotaen** [comment]
Yeah, make sense to draw the line there, and the current highlighting is more than good enough anyways.
